#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Mon Jan  1 13:59:37 2024
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class SCLHelp(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SCLHelp.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((281, 566))
        self.SetTitle("SCL Help")

        self.Panel = wx.Panel(self, wx.ID_ANY)

        sizer = wx.BoxSizer(wx.VERTICAL)

        self.Search = wx.SearchCtrl(self.Panel, wx.ID_ANY, "")
        self.Search.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.Search.SetForegroundColour(wx.Colour(0, 0, 0))
        self.Search.ShowCancelButton(True)
        self.Search.SetDescriptiveText("Find a command...")
        sizer.Add(self.Search, 0, wx.EXPAND, 0)

        self.CMDList = wx.ListCtrl(self.Panel, wx.ID_ANY, style=wx.BORDER_NONE | wx.FULL_REPAINT_ON_RESIZE | wx.LC_REPORT | wx.LC_SINGLE_SEL | wx.LC_VRULES)
        self.CMDList.AppendColumn("Command", format=wx.LIST_FORMAT_LEFT, width=200)
        self.CMDList.AppendColumn("Type", format=wx.LIST_FORMAT_LEFT, width=-1)
        sizer.Add(self.CMDList, 1, wx.ALL | wx.EXPAND, 0)

        self.Panel.SetSizer(sizer)

        self.Layout()
        # end wxGlade

# end of class SCLHelp

class MyApp(wx.App):
    def OnInit(self):
        self.SCLHelpWindow = SCLHelp(None, wx.ID_ANY, "")
        self.SetTopWindow(self.SCLHelpWindow)
        self.SCLHelpWindow.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
